models/user.py
from utilities.helper import cursor, connection


def insert_into_users(data):
    name = data.get('name')
    email = data.get('email')
    password = data.get('password')
    birthday = data.get('birthday')
    age = data.get('age')
    description = data.get('description')

    user_data = (name, email, password, birthday,age,description)
    cursor.execute("""
            INSERT INTO users
            (name,email, password,birthday,age,description)
            VALUES (%s,%s,%s,%s,%s)""", user_data)
    connection.commit()


def login(data):
    email = data.get('email')
    password = data.get('password')
    cursor.execute("""SELECT * FROM users WHERE email=%s AND password=%s""", (email, password))
    return cursor.fetchone()


def find_user_by_email(email):
    cursor.execute("""SELECT * FROM users WHERE email=%s """, email)
    return cursor.fetchone()


def update_user_password(email, password):
    cursor.execute(""" UPDATE users SET password=%s WHERE email=%s """, (password, email))
    connection.commit()


def all_users():
    cursor.execute("""SELECT * FROM users """)
    return cursor.fetchall()


def find_user_by_id(id):
    cursor.execute("""SELECT * FROM users WHERE id=%s """, id)
    return cursor.fetchone()


def update_user(data, id):
    name = data.get('name')
    email = data.get('email')
    password = data.get('password')
    birthday = data.get('birthday')
    age = data.get('age')
    description = data.get('description')
    user_data = (name, email, password, birthday, age, description, id)

    cursor.execute("""
        UPDATE users SET name=%s, email=%s, password=%s, birthday=%s, age=%s, description=%s WHERE id=%s """, user_data)
    connection.commit()

controllers/user_controller.py
# controllers/user_controller.py
from itsdangerous import URLSafeTimedSerializer
from flask import render_template, flash, redirect, url_for, session, jsonify, request
import models.user as user_model
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime, timedelta
import config

MAIL_USERNAME = config.MAIL_USERNAME
MAIL_PASSWORD = config.MAIL_PASSWORD

serializer = URLSafeTimedSerializer(config.SECRET_KEY)


def home():
    return render_template('home.html')


def profile():
    user_name = session.get('user_name')
    email = session.get('email')
    if user_name and email:
        return render_template('user.html', user=user_name)
    else:
        flash("You need to log in first.", 'warning')
        return redirect(url_for('form_bp.home'))


def forgot_password():
    if request.method == 'POST':
        data = request.json
        email = data.get('email')

        user = user_model.find_user_by_email(email)
        if user:
            expiration_time = datetime.utcnow() + timedelta(minutes=1)
            token_data = {'email': email, 'exp': expiration_time.timestamp()}
            token = serializer.dumps(token_data, salt='forgot-password')

            subject = 'Password Reset Request'
            reset_link = url_for('form_bp.reset_password', token=token, _external=True)
            body = f'Click the following link to reset your password: {reset_link}'

            # Create the MIMEText object for the email body
            msg = MIMEMultipart()
            msg.attach(MIMEText(body, 'plain'))

            # Set the email subject and recipients
            msg['Subject'] = subject
            msg['From'] = MAIL_USERNAME
            msg['To'] = email

            # Use your SMTP server to send the email
            try:
                server = smtplib.SMTP(config.smtp_domain, config.smtp_port)
                server.starttls()
                server.login(MAIL_USERNAME, MAIL_PASSWORD)  # Replace with your email and password

                server.sendmail(MAIL_USERNAME, email, msg.as_string())
                server.quit()

                flash('Password reset link sent to your email. Please check your inbox.', 'success')
            except Exception as e:
                print(e)
                flash('Failed to send the reset email. Please try again later.', 'danger')
            message = "Password reset link sent to your email."
            return success_response(True,message)
        else:
            flash('Email not found.', 'danger')
            message = 'Email not found. Try again'
            return success_response(False, message)

    return render_template('home.html')


def reset_password(token):
    try:
        token_data = serializer.loads(token, salt='forgot-password', max_age=3600)
        email = token_data.get('email')
        expiration_time = datetime.fromtimestamp(token_data.get('exp'))

        if datetime.utcnow() > expiration_time:
            flash('The password reset link has expired. Please request a new one.', 'danger')
            return redirect(url_for('form_bp.home'))

    except Exception as e:
        print(e)
        flash('Invalid or expired token. Please try again.', 'danger')
        return redirect(url_for('form_bp.home'))

    if request.method == 'GET':
        return render_template('reset_password.html',user_email=email)


def update_reset_password():
    if request.method == 'POST':
        data = request.json
        email = data.get('email')

        user = user_model.find_user_by_email(email)

        if user:
            password = data.get('password')
            user_model.update_user_password(email, password)

            flash('Password updated successfully')
            message = 'Password updated successfully'
            return success_response(True, message)
        else:
            flash('Password not updated')
            message = 'Password not updated'
            return success_response(False, message)


def logout():
    session.pop('user_name', None)
    session.pop('email', None)
    flash('You have been logged out', 'info')
    return redirect(url_for('form_bp.home'))


def login():
    if request.method == 'POST':
        data = request.json

        user = user_model.login(data)
        if user:
            session['user_name'] = user['name']
            session['email'] = user['email']

            message = 'Login successfully.'
            resp = success_response(True, message)
            # Set the user information in cookies
            resp.set_cookie('user_name', user['name'])
            resp.set_cookie('user_email', user['email'])
            return resp
        else:
            message = 'Invalid email or password.'
            return success_response(False, message)
    else:
        return redirect(url_for('form_bp.home'))


def register():
    if request.method == 'POST':
        data = request.json
        name = data.get('name')
        email = data.get('email')

        try:
            user_model.insert_into_users(data)

            # Set session variables
            session['user_name'] = name
            session['email'] = email

            message = 'Created successfully.'
            resp = success_response(True, message)
            # Set the user information in cookies
            resp.set_cookie('user_name', name)
            resp.set_cookie('user_email', email)
            return resp
        except Exception as e:
            return success_response(False, str(e))
    else:
        return redirect(url_for('form_bp.home'))


def get_all_data():
    if request.method == 'GET':
        all_users = user_model.all_users()

        # response = {
        #     'success': True,
        #     'message': 'User data retrieved successfully',
        #     'users_data': all_users
        # }
        message = 'User data retrieved successfully'
        return success_response(True, message,all_users)


def get_one_data():
    if request.method == 'POST':
        id = request.json.get('id')
        user = user_model.find_user_by_id(id)

        # response = {
        #     'success': True,
        #     'message': 'User data retrieved successfully',
        #     'users_data': user
        # }
        message = 'User data retrieved successfully'
        return success_response(True, message, user)


def update_user():
    if request.method == 'POST':
        data = request.json
        id = data.get('id')
        try:
            user_model.update_user(data,id)
            message = 'Updated successfully.'
            return success_response(False, message)
        except Exception as e:
            return success_response(False, str(e))
    else:
        return redirect(url_for('form_bp.home'))


def page_not_found(error):
    return render_template("error_404.html")


def server_error(error):
    return render_template("error_500.html")


def success_response(success, message, data=None):
    response = {
        'success': success,
        'message': message,
    }

    if data is not None:
        response['resp_data'] = data

    return jsonify(response)

routes/user.py
from flask import Blueprint
from controllers import user_controller
form_bp = Blueprint("form_bp", __name__)

# routes
form_bp.route('/')(user_controller.home)
form_bp.route('/profile')(user_controller.profile)
form_bp.route('/forgot_password',  methods=['POST'])(user_controller.forgot_password)
form_bp.route('/reset_password/<token>', methods=['GET', 'POST'])(user_controller.reset_password)
form_bp.route('/update_reset_password', methods=['POST'])(user_controller.update_reset_password)
form_bp.route('/logout')(user_controller.logout)
form_bp.route('/login', methods=['POST'])(user_controller.login)
form_bp.route('/get_all_data',  methods=['GET','POST'])(user_controller.get_all_data)
form_bp.route('/register',  methods=['POST'])(user_controller.register)
form_bp.route('/get_one_data',  methods=['POST'])(user_controller.get_one_data)
form_bp.route('/update_user', methods=['POST'])(user_controller.update_user)

form_bp.errorhandler(404)(user_controller.page_not_found)
form_bp.errorhandler(500)(user_controller.server_error)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Data Range Picker -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <!-- Bootstrap CSS -->

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename = 'css/style.css')}}">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.10/css/jquery.dataTables.css">

    <title>Hello, world!</title>
  </head>
  <body>


    {% include 'navbar.html'%}
    {% include 'register.html'%}
    {% include 'login.html'%}
    {% include 'forget_password.html'%}


    {% block content%}


    {% endblock %}

    <!-- ckeditor -->
    <script src="{{url_for('static',filename = 'ckeditor/ckeditor.js')}}"></script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS and JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- Data Range Picker -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <!-- Add these lines to include the DataTables CSS and JS files -->
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>


    <script src="{{url_for('static',filename = 'js/register.js')}}"></script>

  </body>
</html>

templates/error_404.html
{% extends 'base.html'%}

{% block content%}
    <div class="d-flex align-items-center justify-content-center vh-100">
        <div class="text-center">
            <h1 class="display-1 fw-bold">404</h1>
            <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
            <p class="lead">
                The page you’re looking for doesn’t exist.
              </p>
            <a href="index.html" class="btn btn-primary">Go Home</a>
        </div>
    </div>
{% endblock %}

templates/error_500.html
{% extends 'base.html'%}

{% block content%}
    <div class="d-flex align-items-center justify-content-center vh-100">
        <div class="text-center">
            <h1 class="display-1 fw-bold">500</h1>
            <p class="fs-3"> <span class="text-danger">Opps!</span> Server Error.</p>
            <p class="lead">
                Try again later
              </p>
            <a href="index.html" class="btn btn-primary">Go Home</a>
        </div>
    </div>
{% endblock %}

templates/forget_password.html
<!-- Modal -->
<div class="modal fade" id="email_modal" data-bs-backdrop="static" data-bs-keyboard="false"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Send Email</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body fixed-modal-body">
                <form id="SendEmailForm">
                    <div class="form-group">
                        <label for="sendEmail">Email:</label>
                        <input
                                type="email"
                                class="form-control"
                                id="sendEmail"
                                placeholder="Enter email"
                                required
                        />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button
                        type="button"
                        id="sendEmailLink"
                        class="btn btn-primary"
                        onclick="sendEmailFunction()"
                >
                    Send
                </button>
            </div>
        </div>
    </div>
</div>

templates/home.html
{% extends 'base.html'%}

{% block content%}

{% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}

<div class="container mt-5">
  <h1 class="mb-4">Blog Post Project</h1>

  <div class="row">
    <div class="col-md-8">
      <!-- Featured Blog Post -->
      <div class="card mb-4">
        <div class="card-body">
          <h1 class="card-title">Featured Blog Post Title</h1>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit....</p>
          <a href="#" class="btn btn-primary">Read More</a>
        </div>
      </div>

      <!-- Add more blog posts as needed -->
    </div>

    <div class="col-md-4">
      <!-- Sidebar -->
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">About the This Website</h5>
          <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit....</p>
        </div>
      </div>
    </div>
  </div>
</div>

    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <table id="userDataTable" class="table mx-auto">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Password</th>
                            <th>Birthday</th>
                            <th>Age</th>
                            <th>Description</th>
                            <th>saveBtn</th>
                            <th>EditBtn</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/login.html
<!-- Modal -->
<div class="modal fade" id="login_modal" data-bs-backdrop="static" data-bs-keyboard="false"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">User LogIn</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body fixed-modal-body">
                <form id="LoginForm">
                    <div class="form-group">
                        <label for="loginEmail">Email:</label>
                        <input
                                type="email"
                                class="form-control"
                                id="loginEmail"
                                placeholder="Enter email"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="loginPassword">Password:</label>
                        <input
                                type="password"
                                class="form-control"
                                id="loginPassword"
                                placeholder="Enter password"
                                required
                        />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="" id="forgetPasswordLink" style="margin-right: auto;" data-bs-toggle="modal"
                   data-bs-target="#email_modal">Forget Password</a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button
                        type="button"
                        id="loginbtn"
                        class="btn btn-primary"
                        onclick="LogInUser()"
                >
                    LogIn
                </button>
            </div>
        </div>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{url_for('form_bp.home')}}">Flasker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                {% if not session.email %}
                <a href="{{url_for('form_bp.login')}}" class="btn btn-outline-success btn-margin" data-bs-toggle="modal"
                   data-bs-target="#login_modal">logIn</a>
                <a href="" class="btn btn-outline-success btn-margin" data-bs-toggle="modal"
                   data-bs-target="#staticBackdrop">Register</a>
                {% elif session.email %}
                <a href="{{url_for('form_bp.logout')}}" class="btn btn-outline-success btn-margin">logout</a>
                {% endif %}
            </form>
        </div>
    </div>
</nav>

templates/register.html
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false"
     aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Register User</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body fixed-modal-body">
                <form id="studentForm">
                    <div class="form-group">
                        <label for="Name">Name:</label>
                        <input
                                type="text"
                                class="form-control"
                                id="Name"
                                placeholder="Enter name"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="Email">Email:</label>
                        <input
                                type="email"
                                class="form-control"
                                id="Email"
                                placeholder="Enter email"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="Password">Password:</label>
                        <input
                                type="password"
                                class="form-control"
                                id="Password"
                                placeholder="Enter password"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="birthday">Birthday:</label>
                        <input
                                type="text"
                                class="form-control birthday"
                                id="birthday"
                                placeholder="Select birthday"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="age">Age:</label>
                        <input type="text" class="form-control" id="age" readonly/>
                    </div>
                    <!-- Add more fields as needed -->

                    <div class="form-group">
                        <label for="text_editor">Description:</label>
                        <textarea
                                id="text_editor"
                                name="text_editor"
                                class="form-control text_editor"
                        ></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button
                        type="button"
                        id="saverUserChangesBtn"
                        class="btn btn-primary"
                        onclick="saveUserData()"
                >
                    Save
                </button>
            </div>
        </div>
    </div>
</div>

templates/reset_password.html
{% extends 'base.html'%}

{% block content%}

<!-- Password Reset Modal -->
<div class="modal fade" id="password_reset_modal" data-bs-backdrop="static" data-bs-keyboard="false"
     aria-labelledby="passwordResetModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="passwordResetModalLabel">Reset Password</h5>
                <a href="{{url_for('form_bp.home')}}" type="button" class="btn-close" aria-label="Close"></a>
            </div>
            <div class="modal-body fixed-modal-body">
                <form id="ResetPasswordForm">
                    <div class="form-group">
                        <div class="form-group">
                            <label for="user_email">Email:</label>
                            <input
                                   type="email"
                                    class="form-control"
                                    id="user_email"
                                    placeholder="Enter email"
                                    required
                                    value="{{ user_email }}"
                                    readonly
                            />
                        </div>
                        <label for="resetPassword">New Password:</label>
                        <input
                                type="password"
                                class="form-control"
                                id="resetPassword"
                                placeholder="Enter new password"
                                required
                        />
                    </div>
                    <div class="form-group">
                        <label for="confirmPassword">Confirm Password:</label>
                        <input
                                type="password"
                                class="form-control"
                                id="confirmPassword"
                                placeholder="Confirm new password"
                                required
                        />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <a href="{{url_for('form_bp.home')}}" class="btn btn-secondary">Close</a>

                <button
                        type="button"
                        id="resetPasswordLink"
                        class="btn btn-primary"
                        onclick="resetPasswordFunction()"
                >
                    Reset Password
                </button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user.html
{% extends 'base.html'%}

{% block content%}

{% for message in get_flashed_messages() %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}

  <h1>this is {{user}} profile page</h1>

{% endblock %}